### ISSUE TITLE
readonly db notworking

### ISSUE THREAD

**Issue by clcc2019** [polardb/polardbx-operator#38]
<img width="1511" alt="image" src="https://github.com/polardb/polardbx-operator/assets/46099295/2ef0208b-9332-4ee7-81d6-17a119b00675">
```yaml

apiVersion: polardbx.aliyun.com/v1
kind: XStore
metadata:
  name: polardb-readonly
spec:
  config:
    controller:
      RPCProtocolVersion: 1
    engine: {}
  readonly: true
  primaryXStore: polardb-master # 主实例名
  topology:
    nodeSets:
    - name: readonly
      replicas: 1
      role: Learner
      template:
        spec:
          image: image
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        xstore/node-role: candidate
                    topologyKey: kubernetes.io/hostname
                  weight: 1
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: mks.components
                        operator: In
                        values:
                          - "enable"
                  weight: 1
          hostNetwork: false
  parameterTemplate:
    name: product-8032
  serviceType: ClusterIP

```
