### ISSUE TITLE
Parameter is not valid

### ISSUE THREAD

**Issue by clcc2019** [polardb/polardbx-operator#42]
The parameters are not effective, such as expire_logs_days, enter mysql to query expire_logs_days is 0

```yaml
apiVersion: polardbx.aliyun.com/v1
kind: PolarDBXParameterTemplate
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: product-8030
spec:
  nodeType:
    cn:
      name: cnTemplate
      paramList:
...
      - defaultValue: "7"
        divisibilityFactor: 1
        mode: readwrite
        name: expire_logs_days
        optional: .*
        restart: true
        unit: INT
...
```
<img width="407" alt="image" src="https://github.com/polardb/polardbx-operator/assets/46099295/f71a6442-c175-431e-8696-88937c22d3d2">
