### ISSUE TITLE
1.7.0执行全量备份报错

### ISSUE THREAD

**Issue by 617450941** [polardb/polardbx-operator#51]
Error from server (Forbidden): error when creating "pxc-backup.yaml": admission webhook "polardbxbackup-validate.polardbx.aliyun.com" denied the request: spec.storageProvider: Invalid value: polardbx.BackupStorageProvider{StorageName:"s3", Sink:"lyfz-polardbx-backup"}: invalid storage, please check configuration of both backup and hpfs  提示这个

备份配置如下
```
apiVersion: polardbx.aliyun.com/v1
kind: PolarDBXBackup
metadata:
  name: lyfz-polardbx-pxcbackup
  namespace: polardbx
spec:
  cluster:
    name: lyfz-polardbx
  retentionTime: 240h
  storageProvider:
    storageName: s3
    sink: lyfz-polardbx-backup
  preferredBackupRole: follower
```

存储配置如下
```
sinks:
   - name: lyfz-polardbx-backup
     type: s3
     endpoint: xxxxxx
     accessKey: xxxx
     accessSecret: xxxxxx
     bucket: lyfz-polardbx-backup
     useSSL: false
   - accessKey: xxx
     accessSecret: xxxxx
     bucket: xxx
     endpoint: xxx
     name: default
     type: oss
   - host: xxxxx
     name: default
     password: xxxx
     port: 22
     rootPath: /xxx
     type: sftp
     user: admin
backupBinlogConfig:
  rootDirectories:
    - /data/xstore
    - /data-log/xstore
cGroupControlConfig:
  cpu_set_strategy: auto
```
