### ISSUE TITLE
no owner found for default/quick-start

### ISSUE THREAD

**Issue by Meizuamy** [polardb/polardbx-operator#55]
使用helm安装polardbx，部署quickstart项目报错：
polardbx-operator：1.7.0
kubernetes: 1.26.12
kubectl: v1.26.12
polardbx：v2.4.1

部署yaml如下：
```yaml
kind: PolarDBXCluster
metadata:
  name: quick-start
spec:
  # PolarDB-X 初始账号配置
  topology:
    nodes:
      gms:
        template:
          image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-engine:v2.4.1_8.4.19
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 2
              memory: 4Gi
      cn:
        replicas: 1
        template:
          image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-sql:v2.4.1_5.4.19
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
      dn:
        replicas: 1
        template:
          image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-engine:v2.4.1_8.4.19
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 2
              memory: 4Gi
      cdc:
        replicas: 1
        template:
          image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-cdc:v2.4.1_5.4.19
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 2
              memory: 4Gi
      columnar:
        replicas: 1
        template: 
          image: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-columnar:v2.4.1_5.4.19
          resources:
            limits:
              cpu: 2
              memory: 4Gi
```

operator-controller 错误信息如下：
```shell
2024-12-09T15:31:34.431+0800    ERROR   controller.polardbx     instance/object.go:122  Unable to get service   {"namespace": "default", "polardbxcluster": "quick-start", "phase": "Pending", "stage": "", "trace": "b452c95e-0bb1-48b7-a3af-c58892d14653", "action": "CreateServicesIfNotFound", "step": 6, "service-type": "readwrite", "error": "no owner found for default/quick-start"}
github.com/alibaba/polardbx-operator/pkg/operator/v1/polardbx/steps/instance.glob..func3
        /workspace/pkg/operator/v1/polardbx/steps/instance/object.go:122
github.com/alibaba/polardbx-operator/pkg/operator/v1/polardbx/steps/instance.init.NewStepBinder.func3
        /workspace/pkg/operator/v1/polardbx/reconcile/adaptor.go:34
github.com/alibaba/polardbx-operator/pkg/k8s/control.(*step).Execute
        /workspace/pkg/k8s/control/step.go:86
github.com/alibaba/polardbx-operator/pkg/k8s/control.(*executor).execute
        /workspace/pkg/k8s/control/executor.go:99
github.com/alibaba/polardbx-operator/pkg/k8s/control.(*executor).Execute
        /workspace/pkg/k8s/control/executor.go:159
github.com/alibaba/polardbx-operator/pkg/operator/v1/polardbx/controllers.(*PolarDBXReconciler).reconcile
        /workspace/pkg/operator/v1/polardbx/controllers/polardbxcluster_controller.go:412
github.com/alibaba/polardbx-operator/pkg/operator/v1/polardbx/controllers.(*PolarDBXReconciler).Reconcile
        /workspace/pkg/operator/v1/polardbx/controllers/polardbxcluster_controller.go:95
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227
2024-12-09T15:31:34.431+0800    ERROR   controller/controller.go:329    Reconciler error        {"controller": "polardbxcluster", "controllerGroup": "polardbx.aliyun.com", "controllerKind": "PolarDBXCluster", "PolarDBXCluster": {"name":"quick-start","namespace":"default"}, "namespace": "default", "name": "quick-start", "reconcileID": "5718bf7a-d94b-481c-a075-a9205039bfcb", "error": "no owner found for default/quick-start"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227
```
